### ISSUE TITLE
incorrectly flags 'wo'

### ISSUE THREAD

**Issue by Captain8771** [Lisenaaaa/powercord-no-swearing#2]
![wo](https://cdn.captain8771.tech/r/5B1CC72ooC.png)

**Comment by Lisenaaaa** [comment]
there's a lot of stuff in here that i didn't know is a swear word or personally wouldn't count as a swear word, such as `poop`, so if stuff like this happens blame the first pr and not me

**Comment by Captain8771** [comment]
was fixed in my PR, closing
